// Code generated by "enumer -type LogLevel loglevel.go"; DO NOT EDIT.

package gotils

import (
	"fmt"
)

const _LogLevelName = "OffFatalErrorWarnDebugInfoAll"

var _LogLevelIndex = [...]uint8{0, 3, 8, 13, 17, 22, 26, 29}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevelIndex)-1) {
		return fmt.Sprintf("LogLevel(%d)", i)
	}
	return _LogLevelName[_LogLevelIndex[i]:_LogLevelIndex[i+1]]
}

var _LogLevelValues = []LogLevel{0, 1, 2, 3, 4, 5, 6}

var _LogLevelNameToValueMap = map[string]LogLevel{
	_LogLevelName[0:3]:   0,
	_LogLevelName[3:8]:   1,
	_LogLevelName[8:13]:  2,
	_LogLevelName[13:17]: 3,
	_LogLevelName[17:22]: 4,
	_LogLevelName[22:26]: 5,
	_LogLevelName[26:29]: 6,
}

// LogLevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LogLevelString(s string) (LogLevel, error) {
	if val, ok := _LogLevelNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LogLevel values", s)
}

// LogLevelValues returns all values of the enum
func LogLevelValues() []LogLevel {
	return _LogLevelValues
}

// IsALogLevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LogLevel) IsALogLevel() bool {
	for _, v := range _LogLevelValues {
		if i == v {
			return true
		}
	}
	return false
}
